"""Add server-owned delivery references without changing legacy artifact bytes."""
from __future__ import annotations

import hashlib
import io
import json
import zipfile

from .capability_contracts import canonical_json
from .plugin_delivery_profile import BLUEPRINT_REFERENCE_PATH, require_delivery_profile
from .plugin_delivery_reference import checked_blueprint
from .scenario_package_artifact import MAX_PACKAGE_BYTES, build_artifact as legacy_build_artifact


def build_artifact(manifest: dict, *, files: dict[str, str] | None = None, plugin_version: str = '1.0.0') -> bytes:
    if 'delivery_profile' in manifest and manifest['delivery_profile'] is None:
        raise ValueError('插件交付规范身份缺失，不能构建')
    profile = require_delivery_profile(manifest.get('delivery_profile'))
    if profile is None:
        return legacy_build_artifact(manifest, files=files, plugin_version=plugin_version)
    blueprint = checked_blueprint(manifest)
    base = legacy_build_artifact(manifest, files=files, plugin_version=plugin_version)
    name = manifest['package_name']
    with zipfile.ZipFile(io.BytesIO(base)) as archive:
        entries = {path.split('/', 1)[1]: archive.read(path).decode('utf-8') for path in archive.namelist()}
    entries[BLUEPRINT_REFERENCE_PATH] = canonical_json(blueprint)
    # Correct only the new profile's template. Human-authored source stays exact.
    if not files or 'README.md' not in files:
        entries['README.md'] = entries['README.md'].replace('capabilities:read', 'capability:read').replace(
            'capabilities:invoke', 'capability:invoke') + (
            '\nRead references/scenario-blueprint.json for the frozen scenario goal, ontology and capability scope. '
            'This reference is generated by the platform; it does not contain runtime inputs or grant permissions.\n'
        )
    if not files or 'skills/run-scenario/SKILL.md' not in files:
        entries['skills/run-scenario/SKILL.md'] += (
            '\nRead ${CLAUDE_PLUGIN_ROOT}/references/scenario-blueprint.json for the frozen goal and selected capability scope. '
            'Skill format, Claude Code hosting, MCP protocol and the platform delivery restrictions are separate contracts.\n'
            'Use the selected workflow semantic.input_bindings and semantic.output_node_keys with the discovered schemas. '
            'Follow client_contract.workflow_completion in references/scenario.json: output.result is an execution trace; '
            'only a successful declared output node with contract_validation="passed" supplies step.result as business output. '
            'Do not assume every succeeded workflow has an end result. If output.status still indicates waiting, '
            'read the same invocation_id with a bounded wait, report pending and do not submit another workflow.\n'
        )
    entries.pop('checksums.json')
    entries['checksums.json'] = json.dumps({path: hashlib.sha256(value.encode('utf-8')).hexdigest()
        for path, value in sorted(entries.items())}, sort_keys=True, indent=2)
    stream = io.BytesIO()
    with zipfile.ZipFile(stream, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
        for path, value in sorted(entries.items()):
            info = zipfile.ZipInfo(f'{name}/{path}', date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            archive.writestr(info, value.encode('utf-8'))
    if stream.tell() > MAX_PACKAGE_BYTES:
        raise ValueError('场景插件超过包大小上限')
    return stream.getvalue()
