"""govern recoverable migration ledger

Revision ID: 20260827_02
Revises: 20260827_01
Create Date: 2026-08-27 12:21:23.736516
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

revision: str = '20260827_02'
down_revision: Union[str, None] = '20260827_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_migration_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('migration_name', sa.String(length=120), nullable=False),
    sa.Column('plan_digest', sa.String(length=64), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('current_phase', sa.String(length=24), nullable=False),
    sa.Column('manifest', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.CheckConstraint("current_phase IN ('plan', 'bootstrap', 'archive', 'import', 'verify', 'cutover')", name='ck_platform_migration_runs_phase'),
    sa.CheckConstraint("status IN ('running', 'failed', 'verified', 'cutover')", name='ck_platform_migration_runs_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('migration_name', 'plan_digest', name='uq_platform_migration_runs_plan')
    )
    op.create_index('ix_platform_migration_runs_status', 'platform_migration_runs', ['status', 'updated_at'], unique=False)
    op.create_table('platform_migration_checkpoints',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('item_key', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.CheckConstraint("status IN ('complete', 'verified')", name='ck_platform_migration_checkpoints_status'),
    sa.CheckConstraint('row_count IS NULL OR row_count >= 0', name='ck_platform_migration_checkpoints_rows'),
    sa.ForeignKeyConstraint(['run_id'], ['platform_migration_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', 'stage', 'item_key')
    )
    op.create_index('ix_platform_migration_checkpoints_status', 'platform_migration_checkpoints', ['run_id', 'status', 'completed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_platform_migration_checkpoints_status', table_name='platform_migration_checkpoints')
    op.drop_table('platform_migration_checkpoints')
    op.drop_index('ix_platform_migration_runs_status', table_name='platform_migration_runs')
    op.drop_table('platform_migration_runs')
    # ### end Alembic commands ###
